baseURL = 'https://blog.kine.cz/'
languageCode = 'en-us'
title = "Kine's info"
theme = "hugo-future-imperfect-slim"
enableRobotsTXT = true
googleAnalytics = "UA-92839335-1"
canonifyURLs = true
assetDir = 'content/assets'
defaultContentLanguage = 'en'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[social]
  GitHub = "kine"
  Linkedin = "kamil-sacek-8830661"
  Twitter = "MVPKine"
  BuyMeACoffee = "kine"
  Email = "kamil.sacek@gmail.com"
    
[params]
  enableCDN             = false
  cssFiles              = ["default","assets/css/copy-code-button.css"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "linkedin", "email"]
  hideEmptyStats        = false
  toc                   = true
  tocWords              = 400
  coverImage            = "assets/DependencyGraph.png"

  [params.meta]
    description         = "Kamil Sacek blog about not only Microsoft Dynamics 365 Business Central but all around like Powershell, Azure DevOps etc."
    author              = "Kamil (Kine) Sacek"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Kine's Info"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Kine's Info"
    paragraph             = "Another blog about Microsoft Dynamics 365 Business Central (AL, Powershell, Azure DevOps etc.)<center><a href='https://mvp.microsoft.com/en-us/mvp/kamil%20sacek-21590'><img src='/assets/MVP_Logo_Horizontal_Secondary_Blue286_CMYK_72ppi.png' width='50%'></a></center>"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic] 
      src                 = "/assets/KSCSmall.png"
      shape               = "circle"
      width               = ""
      alt                 = "Kine's Info"

  [params.sidebar]
    about               = "I have more than 35 years of experience with SW development and everything around IT. I have got my first MVP award in 2005."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = "kinesinfo"
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  [params.staticman]
    enabled             = true
    api                 = "kinesinfo.herokuapp.com"  # No Trailing Slash
    gitProvider         = "github"
    username            = "kine"
    repo                = "KinesInfo_source"
    branch              = "master"

    [params.staticman.recaptcha]
      siteKey           = "6LcsWkMdAAAAAD27lvZOIBkH4TSll08hMxHHLFxs"
      encryptedKey      = "FdlTy3aVy1SZfJ3h9aKAOgqeyZIFjV6Tjk3yN9BXxz5WB6FcmGlafyM+hvBpDzOTstLDgQvBnWIn0T96nMLzI6bUyJL50tfeMuVpkYZhS9VkOhmPq7YEFmZCO7hVYkQkE4hh8JvVtyAmI9WKE5gOHBnRIrLWAFNLz7kUJRu7riOJtj8mNNMlpnfANVaiPQZ6xFykxG2X8RnJRW4dMV/335SiI5QcgB7fZzm0ntYZc1WsnYOUegqgw1z2ttJdB4J0xclKFcowrgKvq1LPn0P7H47EriVwt0QHz9NfK65CA6nJPQ8S487TI635IeXJ8HLOJkYeQnIyMeQZGKavlqDFFA=="
      #siteKey = ""
      #encryptedKey = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = ""
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "categories"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "tags"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 7

#  [[menu.main]]
#    name              = "Contact"
#    identifier        = "contact"
#    url               = "contact"
#    pre               = "<i class='far fa-envelope'></i>"
#    weight            = 6

